<!-- ‘ to ' -->
<!-- ’ to ' -->
<!-- healthspan to health-span -->
<!-- aging to ageing -->
<!-- summarize to summarise -->
<!-- immunization to immunisation  -->
<!-- characterize to characterise -->
<!-- tur isimleri italic, C. elegans, Caenorhabditis elegans, Mus musculus, Homo sapiens, Drosophila melanogaster, D. melanogaster -->

Human life expectancy has been increasing steadily worldwide [@Oeppen2002] and is currently around 80 years of age in developed countries [@Roser2020]. Improvements in the healthcare system, immunisation against infectious diseases, antibiotics, better sanitary measures, housing and lifestyle, resulted in a decline in early life mortality [@Waite2004]. There has also been a significant improvement in late-life mortality, mostly thanks to economic and social developments and ongoing medical advances [@Vaupel2003].

The scientific community has long been discussing whether there is a limit to lifespan [@Barbi2018; @Dong2016; @Oeppen2002; @Olshansky1990; @Olshansky2001; @Olshansky2016]. For example, using conditional probabilities integrating disease data, in 1990 and 2001, Olshansky et al. had suggested the required changes in disease rates are too much to achieve 35 years of additional life expectancy at the age of 50, and thus it is highly unlikely to achieve [@Olshansky1990; @Olshansky2001]. However, female life expectancy at the age of 50 in Japan surpassed this limit [@Oeppen2002]. @Dong2016 used global demographic data and suggested that the survival rates at later ages slow down and maximum lifespan in humans is fixed. A recent study, on the other hand, suggested the mortality rate decreases and essentially reaches a plateau after the age of 105 [@Barbi2018]. Similarly, @Kontis2017 followed a probabilistic Bayesian model averaging (BMA) approach that considers an ensemble of 21 forecasting models and predicted a continued increase in longevity. 

The increase in health-span, *i.e.*, healthy years of life, increases at a slower rate and 16 to 20% of life is spent with multiple diseases [@Jagger2008]. Moreover, the difference between lifespan and health-span is higher in females, and in individuals with a lower socioeconomic status. The force of natural selection declines with age, and thus variants with deleterious effects in late-life accumulate and can cause diseases in the elderly [@Niccoli2012]. Compression of the time spent ill at the end of life by targeting ageing is one of the trends in the ageing research as it becomes more and more clear that it is achievable [@Partridge2018]. There are some 'blue zones' in the world; Okinawa in Japan, Sardinia in Italy, Ikaria in Greece, Nicoya in Costa Rica, and Loma Linda in the US [@Poulain2013]. People living in these regions enjoy increased lifespan and health-span. We have only recently started to live long periods, and thus genetics is not expected to have a significant role in these populations [@Partridge2018]. Indeed, these populations are not genetically different from their neighbours, but their lifestyle and social networks can explain the difference [@Poulain2013]. Diet, education, and physical activity contributes to a more healthy life in human populations [@Crimmins2015]. Another line of evidence for the malleability of life- and health-span comes from the model organism studies. Multiple genetic, environmental, and pharmacological interventions are shown to both increase lifespan and decrease the functional decline in late life [@Fontana2010].

Nevertheless, application of the accumulated knowledge to humans to improve health-span requires a better understanding of the molecular biology of ageing, age-related changes, and age-related diseases. In this thesis, I aim to approach this aim by using computational studies. 

## What is ageing? {#introWhatAgeing}

Ageing is a phenomenon that everybody is familiar with through either observation or experience, yet it is difficult to define. For example, to some, it may only mean an increase in chronological age, mere passage of time. However, to most of the researchers working in the field, ageing is a biological process with specific characteristics. Throughout this thesis, I will also make a distinction between the changes with chronological age and ageing. I will consider ageing as a process that starts after the average age at first reproduction, and the time before then as postnatal development. The reasoning comes from the evolutionary theories stating that the force of natural selection is the highest before reproductive time (see Section \@ref(introEvoAgeing)). 

In the literature, ageing is often defined as the time-dependent functional decline, increased susceptibility to pathologies, and an increased risk of death [@Lopez-Otin2013]. While I strongly agree with this definition, I want to state that ageing-related changes observed through high-throughput experiments are not necessarily always detrimental. Instead, they may include neutral or beneficial changes as a response to harmful effects seen during ageing [@Kowald2016]. Unfortunately, the characterisation of these changes is still lacking. Thus, even though, in principle, I would consider only the processes that result in functional decline as contributors of ageing, in practice, all age-related changes after the age of puberty is considered as ageing-related changes in the upcoming chapters. The challenges and results of this ambiguity are further discussed in the relevant chapters. 

## Evolution of ageing {#introEvoAgeing}

If ageing results in a decline in organismal fitness and an increase in the risk of mortality, how could it survive through evolution, and how is it seen in most animals? There have been more than 300 theories of ageing [@Medvedev1990], and many attempted to answer this question. Overall, we can classify them into two as programmed and non-programmed theories of ageing. Today, the mainstream opinion favours the non-programmed theories [@Austad2004]; however, I will briefly describe both categories. 

### Programmed theories of ageing {#introProgAgeing}

The programmed theories of ageing suggest that functional decline in post-reproductive age and shorter lifespan confers evolutionary benefit and thus is evolved under selection. This could be driven to prevent post-reproductive individuals from competing for resources or to increase genetic diversity and the speed of evolution by increasing the number of generations. There are three main counter-arguments against programmed theories, and these are presented and reviewed multiple times by Tom Kirkwood and his colleagues [@Kirkwood1977; @Kirkwood2005; @Kirkwood2011; @Kowald2016]. The first counter-argument is that although ageing is almost universal for many species in captivity [@Flatt2018], it is rarely observed in the wild. In natural conditions, mortality is generally due to extrinsic factors (*e.g.* predation and pathogens), and rarely caused by ageing-related mortality. Thus, ageing-related mortality cannot be under selection. This argument has been challenged by recent field studies documenting that multiple species experience ageing in the wild [@Brunet-Rossinni2005; @Nussey2013]. The second counter-argument is that if ageing were programmed, there would be a limited number of genes controlling ageing. This argument was challenged by the discovery of genes and pathways that modulate lifespan. However, these genes only postpone the ageing process and do not eliminate it. Last and probably, the most persuasive argument is that these theories are based on group selection, which is much weaker than selection on individuals, except for a few special conditions [@Smith1976]. If there were factors that accelerate ageing because of its benefits for the species, they would not be selected as their disadvantageous effects on individuals would override the selection at the group level.

### Non-programmed theories of ageing

Non-programmed theories suggest that ageing is non-adaptive, and is a result of either decreasing natural selection or is a side-effect of the selective pressure on other traits [@Flatt2018]. The force of natural selection at different ages can be described as a function of reproduction and extrinsic mortality [@Kirkwood2011]. As age increases, especially after the age of reproduction, the force of natural selection is predicted to decline because of extrinsic hazards. There are two main evolutionary genetic theories of ageing that are based on population genetics principles, *i.e.* mutation accumulationand antagonistic pleiotropy theories of ageing. Mutation accumulation theory of ageing (MA) predicts an intergenerational accumulation of deleterious variants in the population if they are only expressed (*i.e.* functional) at a late age [@Medawar1953]. Antagonistic pleiotropy theory of ageing (AP) focuses on pleiotropic variants that have opposite effects on multiple traits. If the variant is beneficial for a trait that is important when the force of natural selection is strong, *e.g.* survival or reproductive success, these variants would be favoured to be passed on the future generations despite their detrimental effects in late age [@Williams1957]. A modified version of AP that is expressed in terms of physiological trade-offs is the disposable soma theory. It is based on the principle that cellular resources are limited and are distributed between growth, reproduction, and maintenance. Thus, greater investment in growth and reproduction would result in reduced investment in maintenance, which would result in the accumulation of cellular damages [@Kirkwood1977]. 


The discovery of genes and pathways that regulate lifespan in model organisms had challenged the non-adaptive theories of ageing [@Johnson2002]. However, the fact that these genes are mostly in pathways that sense the environmental resources (*e.g.* nutrient-sensing network (NSN), mTOR / PI3K pathway) or regulate genetic maintenance (*e.g.* DNA repair genes) supports the notion that these genes do not control the ageing process, but instead regulate the resource allocation [@Kirkwood2011]. Moreover, none of these genes causes complete abolition of ageing, but they rather postpone the process, which supports the predictions of non-programmed theories. 

## The hallmarks of ageing {#introHallmarks}

The first signals that genetics may play a role in modulation of lifespan started to emerge around 40 years ago when the first long-lived strains of *Caenorhabditis elegans* were isolated [@Klass1983]. The genetic element first discovered to modulate lifespan was *age-1*. However, the impact of this gene was controversial as it also affects total food intake and possibly causing caloric restriction. Later, Friedman and Johnson showed 65% lifespan extension was due to the mutation itself, not a reduction in the caloric intake [@Friedman1988]. Ten years later, Kenyon et al. showed *daf-2* mutant worms also have potential to double their lifespans and more importantly without a cost on their reproductive success [@Kenyon1993].  *daf-2* also codes for a protein in the NSN, a homologue of IGF-1 receptor in humans. Many other discoveries followed these and scientists found different pathways regulating lifespan in model organisms. @Lopez-Otin2013, later reviewed these genetic elements together with the changes that occur in physiological ageing in mammals to compile a set of characteristics that define the ageing phenotype. Authors considered three criteria to consider these characteristics as hallmarks: i) they should manifest themselves in physiological ageing, ii) their experimental exacerbation should worsen the ageing phenotype, and iii) their reduction should improve lifespan or at least delay functional decline. Not all of the molecular changes can be tested extensively in multiple organisms, and some of the hallmarks do not satisfy all three. Another layer of complexity comes from the interconnectedness between hallmarks as they are not independent. Nevertheless, the list of 9 hallmarks presents the functional characteristics associated with ageing. 

### Primary Hallmarks {#introPrimaryHallmarks}

These are the hallmarks that explain likely causes of cellular damage. These have adverse effects on the functionality, and their reduction would ameliorate the ageing process.

**Genomic instability:** DNA integrity and stability are threatened by various intrinsic (*e.g.* DNA replication errors, reactive oxygen species (ROS)), or extrinsic (*e.g.* UV radiation, cancerogenic factors) factors throughout life [@Hoeijmakers2009]. These result in point mutations, translocations, chromosomal abnormalities like aneuploidy that can affect the structure or regulation of essential genes and result in a decrease in the functional capacity of cells [@Faggioli2012; @Forsberg2012; @Garcia-Nieto2019]. Genes functioning in the DNA repair mechanisms have been found important for physiological ageing [@Gorbunova2007] as well as accelerated ageing syndromes [@Kubben2017]. 

**Telomere attrition:** While the accumulation of somatic damage throughout the genome seems to be random, telomeres are the primary sites being affected during ageing [@Blackburn2006]. DNA polymerase cannot replicate the ends of linear DNA molecules and, in the absence of telomerase, the telomere region gets shortened in each replication [@Shay2018]. Most mammalian species lack telomerase in somatic cells, and thus telomere attrition is one of the characteristics of ageing. This also limits the number of possible replications and leads to replicative senescence [@Hayflick1961; @Olovnikov1996]. Shorter telomeres are associated with shorter lifespan [@Boonekamp2013], and induced telomerase activity rescues this phenotype [@Jaskelioff2011]. 

**Epigenetic alterations:** Just like somatic genetic mutations, epi-mutations can result in disruption of cellular activities [@Talens2012]. Characteristic changes in the epigenome involve global DNA hypomethylation, region-specific DNA hypermethylation, and histone modifications [@Pal2016]. These changes are also used to develop the epigenetic ageing clock, the most accurate age-predictor today (see Section \@ref(introOtherOmics)) [@Horvath2018]. The epigenome is vital for the regulation of gene expression and disruptions can result in a decrease in functional capacity. While genetic mutations are mostly irreversible, understanding the epigenome-wide changes can offer ways to intervene in ageing-related phenotypes [@Freije2012; @Rando2012]. 

**Loss of proteostasis:** Proteostasis, or protein homeostasis, is the sum of all activities to ensure the stability and functionality of the proteome. It involves many regulators, including molecular chaperones, protein posttranslational modification enzymes, proteasome, and lysosome [@Hipp2019]. Accumulation of nonfunctional and misfolded proteins is a characteristic of physiological ageing and age-related diseases, especially neurodegenerative diseases such as Alzheimer's and Parkinson's [@Klaips2018]. Improvement of proteostasis through experimental interventions delayed ageing in mammals [@Zhang2008]. 

### Antagonistic Hallmarks

This category involves hallmarks that might have positive or negative effects depending on the intensity. They generally occur as a response to the primary hallmarks, and when their amplitude or duration is excess, they result in pathological consequences. 

**Deregulated nutrient sensing:** Genes and proteins functioning in the nutrient-sensing network (NSN) have been shown to modulate life-, and health-span in model organisms [@Fontana2015]. In general, anabolism accelerates the ageing process and decreases lifespan [@Fontana2010]. In line with this observation, dietary restriction improves lifespan in a wide range of organisms (see Section \@ref(introInterventions)) [@Colman2014; @Mattison2012]. 

**Mitochondrial dysfunction:** Ageing-related accumulation of ROS, and mutations in the mitochondrial DNA result in the disruption of the energy metabolism and decreased ATP availability [@Green2011; @Kauppila2017]. A limited amount of ROS was observed to trigger mitohormesis, a process that prevents further damage. Thus, while a small amount of ROS can activate protective mechanisms, the excess can disrupt energy metabolism [@Balaban2005].



**Cellular senescence:** Broadly, cellular senescence can be defined as cell cycle arrest upon various triggers, such as telomere attrition and oncogene activation [@Campisi2007]. Cellular senescence prevents the accumulation of damaged cells by preventing further divisions. However, the senescent cells also secrete various proinflammatory molecules (senescence-associated secretory phenotype, SASP), that in turn cause neighbouring cells to become senescent [@Rodier2011]. Because it prevents nonfunctional cells from dividing and accumulating, inducing cellular senescence in modest levels may improve lifespan [@Matheu2009]. However, eliminating the senescent cells that accumulate with age also extends lifespan [@Childs2017]. 



### Integrative Hallmarks

These are the results of the previously mentioned hallmarks. They induce system-level changes and result in an overall ageing phenotype that causes a decline in the organism's functional capacity. 

**Stem cell exhaustion:** Decline in tissues' proliferative capacity is one of the well-known characteristics of ageing [@Goodell2015]. As a result of the multi-layered accumulation of damage, tissues lose their regenerative capacity [@Janzen2006; @Rossi2007]. Improving the division capacity of the stem cells may improve lifespan at the organismal level [@Rando2012]. 

**Altered intracellular communication:** Apart from cell-intrinsic changes, hormonal and non-hormonal intercellular communication is also disrupted with age [@Russell2007; @Zhang2013]. Inflammaging, which is a continuously inflamed state of aged tissues, is one of the characteristics of ageing and it is triggered by the pro-inflammatory signals, inefficient clearing of pathogens and their hosts, and SASP [@Franceschi2018]. Coordinated functional decline in multiple organ systems is also observed through communication via gap-junctions, cell-to-cell contacts, and other signalling channels [@Durieux2011; @Nelson2012]. Blood-borne interventions, such as parabiosis, offer opportunities to modulate lifespan at the intercellular level [@Conboy2005; @Villeda2011].

## High-throughput 'omics' studies of ageing {#introOmics}

The majority of today's knowledge about ageing and regulation of lifespan has been driven by the genetic studies on model organisms, investigating how genetic perturbations influence lifespan. A relatively recent development has been the advances in the high-throughput technologies, allowing the study of physiological ageing at the molecular level. In this section, I summarise some of the evident conclusions driven by these high-throughput omics studies focusing on ageing in humans. 


### Genomics

High-throughput measurements became first available for genomics. Using chips designed to capture specific single nucleotide polymorphisms, or later using DNA sequencing technologies, it became possible to resolve genetic variation at a single nucleotide level.

#### Germline mutations and longevity

The heritability of longevity estimated to be only 20-25% [@Deelen2013; @Murabito2012]; however, many age-related diseases which influence health-span and longevity have rather high heritability estimates. For example, Alzheimer's show 60-80% heritability [@VanCauwenberghe2016], and cataract has around 50% [@Hammond2000]. 

Studies comparing centenarians, *i.e.* people reaching 100 years of age, with younger controls found several candidate genes influencing longevity, including *CDKN2A/B* and *APOE* genes and FOXO transcription factors which were found repeatedly in independent studies [@Deelen2013; @Partridge2018; @Pilling2017; @Wright2019]. Despite the relatively low heritability of longevity, studies using parental longevity as a proxy to individual longevity also replicated these results and suggested other candidates, which were also associated with late-onset diseases [@Deelen2019]. 

#### Somatic mutation accumulation with age

Spontaneous stochastic mutations occur in somatic cells throughout life. Most of them are thought to be harmless, but some may occasionally affect a gene or its regulation, leading to functional consequences. The role of somatic mutations and cancer is better understood today [@Martincorena2015]. Some non-malignant neurological diseases, such as cerebral cortical malformation, epilepsy, autism spectrum disorder, are also related to somatic mutations that occur early in life [@Rodin2018]. Progressive accumulation of somatic mutations are proposed to contribute ageing [@Lopez-Otin2013]; however, the characterisation of the extent requires improved sequencing technologies. 

The somatic mutation rate in human B and T lymphocytes, fibroblasts, retina, and the intestinal epithelium is estimated to be in the order of 2 to 10 mutations per diploid genome per cell division, which is ten times more than germline mutations [@Lynch2010; @Martincorena2015]. Using whole-genome/exome sequencing, single-cell DNA sequencing, or RNA sequencing technologies, studies showed that somatic mutations occur stochastically but are affected by the underlying genetic programs such as biases in the DNA repair mechanisms, can lead to clonal expansion as in cancer, and can involve cancer driver mutations [@Lodato2020; @Risques2018]. Moreover, mutation landscape is tissue-specific, but genes whose expression is associated with increased mutation load in multiple tissues include DNA repair, immune response, autophagy, and cell adhesion [@Garcia-Nieto2019].

### Transcriptomics 

Genes are transcribed into RNA molecules, and the total of these transcripts are called transcriptomics. It includes both coding and non-coding RNA molecules. Similar to genomics, both microarrays and sequencing methods are used to measure the abundance of transcripts in the cell. Most of the studies have a cross-sectional design, *i.e.* have multiple samples at different ages, to measure how the expression of genes changes with age. Most of the human studies have a limited sample size, and thus, replication is an issue [@Valdes2013]. Although the genes that show an increase or decrease in expression with age do not overlap well, studies agree on overall up- and down-regulated pathways. However, these pathways show a high tissue-specificity. Blood tissue shows significant changes in immune regulated pathways and apoptosis [deMagalhaes2009; @Peters2015]. Brain tissue is associated with changes in synapse-related genes [@Berchtold2008; @Colantuoni2011; @Kang2011]. Down-regulation of mitochondrial genes, on the other hand, is observed across multiple tissues [@Valdes2013]. Age-related change in transcriptome is not limited to abundances but also involves expression of different isoforms. Both the most abundant isoform and the number of co-existing isoforms change with age,  especially in the brain tissue [@Bhadra2019]. 

Most of the transcriptome studies for ageing focus on one species at a time, and investigate one of the most widely used laboratory organisms [@Stegeman2017; @McCarroll2004], humans [@Glass2013; @Colantuoni2011; @Lu2004], or long-lived species such as naked mole-rat [@Kim2011] or bowhead whale [@Seim2014]. However, natural lifespan is highly variable across species and could be investigated to understand what contributes to a longer lifespan. The biggest of these studies analyzed gene expression in kidney, brain and liver of 33 mammals [@Fushan2015] and found a parallel evolution of gene expression and lifespans. More specifically, they identified a positive correlation between lifespan and expression of genes involved in DNA repair, immune response, and damage response. They also showed down-regulation of lipid metabolism, TCA cycle, and amino acid degradation with increased lifespan. Another study used primary skin fibroblasts from rodents, bats, and a shrew and again found DNA repair as up- and proteolysis as down-regulated with increased lifespan. However, it is important to note that these studies compare gene expression in adult organisms and do not consider the regulation of gene expression across the lifespan. 

The studies I described so far use bulk tissue, and thus, whether these changes are cell-autonomous or due to the changes in the cellular composition is not clear. Recent developments in single-cell sequencing technology allowed to measure gene expression levels in a single cell. The number of human studies using scRNAseq is minimal. Nevertheless, they suggest that both the changes in cell-type composition and cell-specific changes contribute to the age-related changes observed using bulk tissue [@Darmanis2015; @Enge2017]. A recent study sampling multiple tissues at different ages in *Mus musculus* suggested distinct cell types undergo different ageing trajectories, but similar cell types in different tissues show similar changes; thus ageing and cell-type identity are coupled [@Kimmel2019]. 

Here I summarised the transcriptomics studies focusing on coding transcripts, however, there are several studies suggesting non-coding RNAs such as miRNAs [@DankaMohammed2017; @Kinser2019; @Victoria2017], circRNAs [@Knupp2018; @Mahmoudi2019], lncRNAs [@Bink2019; @Marttila2020; @Sousa-Franco2019] also show changes with age and control some of the critical regulators of longevity. 

### Other omics {#introOtherOmics}

**Epigenomics** is the total of chemical compounds that change the DNA regulation without altering the base sequence. This can be achieved by modifying the DNA or histone proteins. Epigenome undergoes substantial changes with age, including a global DNA hypomethylation, regional DNA hypermethylation, and histone modifications [@Pal2016], and global heterochromatin loss [@Tsurumi2012]. The first studies identified specific CpG sites that show differential methylation between young and old in different tissues and cell types [@Bork2010; @Rakyan2010; @Teschendorff2010]. Moreover, one of the characteristic observations in the age-related change in DNA methylation is the increase in inter-individual variability (see Section \@ref(introHeterogeneity)), which is called 'epigenetic drift' [@Teschendorff2013]. Despite this increased heterogeneity, DNA methylation offers the most accurate biomarkers of ageing. @Bocklandt2011, for the first time, showed that epigenetic changes in only two CpG sites could predict the chronological age with 5.2 years of error. After this pioneering study, many different epigenetic clocks are designed for different tissues or species. @Horvath2013 and @Hannum2013 epigenetic clocks constitute the most accurate biomarker of human ageing so far with 3.6 and 4.9 years of mean absolute errors. In these models, the deviation from the chronological age is interpreted as acceleration or deceleration of ageing process and is associated with a wide range of health-related conditions, such as cancer, obesity, menopause, Werner syndrome, Huntington's disease [@Horvath2018].

**Proteomics** is the study of the entirety of the proteins, their alternative isoforms and modifications. Due to alternative splicing and post-translational modifications, the number of proteins is estimated to be two orders of magnitude higher than the coding transcripts. However, due to technical challenges, only a small fraction of proteins or their variants are examined. Although only around 3000 proteins could be examined, sampling more than 4000 individuals, @Lehallier2019 showed the changes in proteome are not linear but show changes in direction, as also reported for transcriptome and proteome studies with much smaller sample size [@Anisimova2020; @Colantuoni2011; @Donertas2017; @Somel2010]. Although the number of proteins that could be investigated is limited, previous studies also report that the changes in protein abundance mostly reflect transcript abundances [@Ori2015; @Somel2010], however translational efficiency impacts the protein abundance [@Ori2015]. Moreover, the composition of key protein complexes, such as nuclear pore complex, polycomb repressive complex, exon junction complex, and complexes involved in vesicular transport, changes with age; potentially leading to misassembly or change in functionality  [@Ori2015]. 

**Metabolome**, which encompasses low-molecular-weight molecules in a biological system, also shows substantial changes with age. Studies report age-related changes in two-thirds of the entire metabolomic content measured [@Menni2013; @Yu2012]. The changes are also associated with a wide range of age-related functional decline, including changes in bone mineral density, cholesterol levels, cancer, and type 2 diabetes [@Zierer2015].

**Microbiomics** investigates all of the genetic material and their products within the entire collection of microorganisms in a given environment. The majority of ageing research focuses on intracellular molecular changes with age; however, there is growing evidence that the gut microbiome changes with age and in ageing-related diseases [@Buford2017]. The human gut is inhabited by over 1000 microbial species, which have co-evolved with humans to live together with mutual benefit. These microbial communities are involved in various processes, including modulation of the nutrient absorption, insulin signalling pathway, overall metabolic state, and the immune system, which are also implicated in ageing [@Seidel2018]. During ageing, the interaction between host and gut microbiota disrupts, leading to dysbiosis and infections [@Aleman2019]. There is some inconsistency about which microbial families in the human gut are affected the most as changes in lifestyle, background population, and antibiotic usage that accompany ageing can influence the populations as well. Nevertheless, all studies agree that the microbial diversity decreases with age [@OToole2015]. Older ages are associated with an increased number of pathogenic species and a reduced number of short-chain fatty acid-producing bacteria [@Smith2017]. The permeability of intestinal epithelial barrier also increases in diverse species (with a limited proof in humans), and likely causes chronic inflammation [@Camilleri2019]. The experiments in mice and killifish show microbiota transfer from young to old individuals have effects on both age-related phenotypes and lifespan and suggest that the age-associated changes in gut microbiota play a functional role rather than being just a correlation [@Kundu2019; @Smith2017]. Disruption of the stability in gut microbiota contributes to various food allergies and inflammatory bowel disorders. However, in recent years it became evident that the changes in microbial composition are relevant for even organs distant from the intestine. Diseases associated with changes in the microbial composition include colon cancer, Parkinson's and Alzheimer's diseases, obesity, diabetes, cardiovascular conditions, frailty, osteoporosis, gout, rheumatoid arthritis, majority of which are age-related conditions [@Buford2017].

### Heterogeneity in molecular changes associated with age {#introHeterogeneity}

Despite the ubiquity of ageing in all living organisms, the molecular mechanisms responsible still require further elucidation. Ageing differs phenotypically among individuals, including monozygotic twins [@Herndon2002; @Kirkwood2005], and within tissues from the same individuals [@Horvath2013]. Researchers have observed an age-related increase in variability in the epigenome [@Cheung2018; @Fraga2005] and transcriptome [@Somel2006] of genetically identical samples, which may underlie the phenotypic differences. Age-related expression variability has been detected in many different cells, and tissue types including mice stem cells, cardiomyocytes and immune cells [@Bahar2006; @Hernando-Herraez2019; @Martinez-Jimenez2017], rat neural retina [@Li2009], fruit-fly, mice and human brain [@Angelidis2019; @Brinkmeyer-Langford2016; @Davie2018; @Somel2006; @Ximerakis2019] as well as human pancreas, lung, blood, skin, fat and human fibroblasts in vitro [@Angelidis2019; @Enge2017; @Vinuela2018; @Wiley2017]. Despite these reports, there is no agreement on the underlying mechanisms, extent and functional consequences. Suggested mechanisms include somatic [@Bahar2006; @Enge2017] and germline mutations [@Brinkmeyer-Langford2016; @Vinuela2018], changes in the DNA methylation [@Hernando-Herraez2019; @Slieker2016; @Vinuela2018] and chromatin modifications [@Cheung2018] and resulting chromatin compaction [@Davie2018] as well as global dysregulation, caused by the change in a transcription factor or miRNA expression [@Inukai2018]. Both genome-wide and hypothesis-driven approaches have been employed to explore the extent of expression variability with age. Among the former, some show a transcriptome-wide increase [@Angelidis2019; @Davie2018; @Enge2017; @Hernando-Herraez2019; @Somel2006], while others focus only on those genes showing significant changes in their variability. @Brinkmeyer-Langford2016 report that an equal number of genes significantly increase or decrease their expression variability, whereas a recent study from @Vinuela2018 shows more genes decreasing rather than increasing their expression variability. Hypothesis-driven studies mostly show an increase in variability for the genes measured [@Bahar2006; @Martinez-Jimenez2017; @Wiley2017], whereas @Warren2007 suggest this might be specific only to the non-renewing tissues. Similarly, @Ximerakis2019 show that change in transcription variability is in different directions in different cell types of the mouse brain. The reports also vary in terms of the functional association of this variability. While some consider that increase in variability is widespread [@Davie2018; @Somel2006], others report that variability is concentrated in various cellular functions [@Brinkmeyer-Langford2016; @Li2009; @Slieker2016] – although these functions also differ between reports. In Chapter \@ref(HeterogeneityChapter), I present an analysis of the extent and functional associations of the age-related change in gene expression heterogeneity in the human brain. 

## Ageing and diseases {#introAgeingDisease}

Ageing is the major risk factor for many diseases. Increase in life expectancy poses a threat to both individuals and society, considering that late-life is generally associated with multiple diseases. Thus, it is vital to elucidate the nature of the relationship between ageing and diseases.

Many diverse diseases have an increased risk with age, including cardiovascular, neurodegenerative, metabolic diseases, and cancer [@Niccoli2012; @Partridge2018]. However, even before the diagnosis of diseases, structural, mechanic, and endocrine changes occur throughout the body. For example, age-related changes in bone density, muscle mass, strength, cognitive abilities, hormone levels, insulin resistance, and vascular stiffness can result in medically defined diseases at later ages. 

Although these diseases involve different organs and pathologies, they all show a strong dependence on age [@Niccoli2012] and could, therefore share common etiologies based upon the underlying mechanisms of ageing. It is therefore essential to understand if the ageing process itself leads age-related detoriation in common pathways and thus different age-related conditions, or if these diseases instead have independent causes. Previous studies have suggested the presence of common pathways that are associated with different age-related diseases. A computational study, comparing GWAS summary results for different age-related diseases has shown that pathways such as proteostasis and NSN are associated with various age-related diseases at the pathway level [@Johnson2015]. Similarly, independent studies have shown the importance of NSN in cardiovascular diseases [@Nishimura2011] and neurodegeneration [@Bove2011]. A comprehensive review on the role of ageing-related pathways in age-related diseases suggests that not only NSN but mitochondrial function, DNA damage response and autophagy pathways are also linked to age-related diseases [@Niccoli2012]. Components of the proteostasis system have also been repeatedly shown to have a role in many age-related diseases including but not limited to ALS, Alzheimer's, cataracts, cardiomyopathy, cardiovascular disease, frontotemporal dementia, and type II diabetes [@Kaushik2015]. 

The unhealthy proportion of life at late ages, often with more than two diseases (*i.e.* multimorbidity) [@Kingston2018; @Marengoni2011; @Violan2014], and the use of multiple drugs for treatment (*i.e.* polypharmacy) [@Bushardt2008; @Gu2010; @Guthrie2015; @ParameswaranNair2016] poses challenges for the individuals, their carers and social networks, and healthcare systems. Limiting the effect of the unhealthy proportion at the end of life is a high priority for the researchers, national governments, and international health organizations [@WHO2015]. A plausible idea is to target ageing to alleviate the effect of multimorbidity and associated polypharmacy at late ages. However, this assumes that multiple diseases have a common underlying factor that can be attributed to age-related changes. There are a few studies investigating the link between ageing and age-related diseases. However, to our knowledge, as a part of this thesis, I present the most comprehensive and systemic analysis of diseases that are clustered based on their age-relevance using an unbiased data-driven approach in Chapter \@ref(UKBBChapter).

## Pharmacological interventions to improve life- and health-span {#introInterventions}

The genetic studies showed that the lifespan of model organisms could be modulated [@Kenyon2010]. Later studies showed lifespan could be extended not only through genetic modifications but also by environmental perturbations, more specifically through dietary restriction [@Fontana2010]. Dietary restriction (DR), restricted food intake without malnutrition, can improve both life- and health-span in diverse organisms [@Fontana2015; @Kapahi2017]. DR has been shown to reduce plasma triglycerides, diabetes, cardiovascular disease, neoplasms, and brain atrophy in rhesus macaque [@Colman2014; @Mattison2012]. NSN, including insulin/insulin-like growth factor and mTOR signalling pathways, monitor the changes in diet. Genetic perturbations that reduce the activity of NSN have led to improved lifespan in diverse organisms  [@Fontana2010; @Kenyon2010; @Pan2017]. This, in turn, directed the attention to finding pharmacological interventions that improve health- and lifespan. *Could it be possible that we take some drugs and live longer and healthier?*



Model organism studies suggest that there are at least several chemical compounds that can improve lifespan in diverse species. Moreover, combinations of drugs acting on separate pathways or branches of pathways can be used to achieve even longer lifespan [@Admasu2018; @Castillo-Quan2019]. As of March 2020, DrugAge, which is a  literature-based database of chemical compounds that modulate lifespan in model organisms, harbours 567 unique drugs that modulate lifespan of at least one model organism [@Barardo2017]. Not all of these compounds have a considerable influence on the lifespan of multiple organisms, but there are a few that are repeatedly shown to extend lifespan in independent studies. Here, I summarise three that has been tested in *Caenorhabditis elegans*, *Drosophila melanogaster*, and *Mus musculus* and recorded 20% extension in average lifespan in at least one experiment:

**Rapamycin:** Rapamycin, or sirolimus, inhibits the mTOR Complex 1 (TORC1) activity and is used after tissue transplants to prevent rejection [@Sirolimus]. Shortly after the first discovery of the importance of mTOR signalling in ageing [@Kapahi2004; @Vellai2003], lifespan extension by rapamycin was shown in diverse organisms, including yeast [@Kaeberlein2005], worm [@Robida-Stubbs2012], fly [@Bjedov2010], and mice [@Harrison2009]. It also alleviates many age-related conditions in ageing mice [@Kennedy2016]. All seven studies that are recorded in DrugAge database and use the three model organisms mentioned above extended lifespan [@Barardo2017]. 


**Metformin:** Metformin is a drug used to treat type 2 diabetes [@Metformin]. There are multiple ageing-related mechanisms targeted by metformin. In essence, it decreases insulin levels, decreasing IGF-1 signalling [@Liu2011], inhibits mTOR [@Kickstein2010], inhibits mitochondrial complex 1, reducing endogenous ROS production [@Batandier2006], activates AMPK [@Foretz2014], and reduces DNA damage [@Algire2012]. However, it is not yet clear if the effect of metformin on lifespan is through multiple independent pathways or the effects are downstream of one primary action [@Barzilai2016]. Moreover, metformin reduces all-cause mortality in people with diabetes compared to the ones receiving non-metformin therapies [@Campbell2017] and is under clinical trials for protection against the effects of ageing [@Barzilai2016; @Espeland2016]. 62% of 13 studies on the three model organisms that are recorded in DrugAge extended lifespan [@Barardo2017]. 



**Resveratrol:** Resveratrol is a compound found in red wine. It is not an approved drug, though it is being investigated to treat cold sores [@Resveratrol]. Since 1992, there have been several reports showing cardioprotective, anti-cancer, stress-resistance effects of resveratrol, as well as its capacity to extend lifespan [@Baur2006]. The mechanism of action of resveratrol remains controversial. Early studies suggested it acts directly by activating *SIRT1*. However, recent studies suggest that *SIRT1* is activated by the inhibition of cAMP phosphodiesterase [@Novelle2015]. Nevertheless, direct or indirect, resveratrol seems to act through activation of sirtuins, which are NAD$^+$-dependent deacetylases, and promote survival and stress resistance [@Baur2006]. Only 50% of 32 studies using the three model organisms that are recorded in DrugAge database extended lifespan [@Barardo2017]. 


Recent computational developments and high-throughput testing technology also allowed a new area of research: computational drug repurposing. Instead of designing new compounds that target key contributors of a disease / phenotype, drug repurposing strategies search for drugs that are already in use or designed for other conditions but could be used for a new purpose, ageing in our case. There are already a few studies in this area, and as part of this thesis, I present a new approach in Chapter \@ref(drugChapter), together with a comparison of different methods developed to achieve this aim.

### Challenges involved in drug studies

Several drugs have been shown to extend lifespan in model organisms; however, a significant challenge remains to be the reproducibility of the effects. As noted in the previous section, although there are many candidates, only three had been found to extend lifespan in multiple organisms, and even they do not have a very high reproducibility (50%, 62%, and 100% of the studies extended the average lifespan of tested organisms). NIA Interventions Testing Program (ITP) is a critical multi-institutional program aiming to test the effects of chemical or environmental perturbations on the lifespan of genetically heterogeneous mice [@Nadon2016]. The program aims to increase reproducibility and find candidates to modulate ageing. 

Although some of the candidates indicate potential use for lifespan extension, their effects in humans are difficult to assess experimentally. We need access to human data in old ages, longitudinal data enabling advanced computational modelling, and reliable biomarkers of ageing. The need for biomarkers of ageing is becoming ever more critical to allow a rapid assessment of the effects of a drug on an organism other than by conducting lengthy, expensive lifespan experiments. The emergence of several 'epigenetic ageing clocks' [@Hannum2013; @Horvath2013; @Levine2018] provides opportunities to monitor ageing in both cells and organisms actively. Combining molecular, clinical, and lifestyle data is crucial to model the effects of drugs in humans [@Donertas2019].

Moreover, even though the targets of the candidates are highly conserved, we see that their effects on lifespan change drastically between organisms. Drugs have much more notable effects on short-lived species such as *C. elegans* and *D. melanogaster* than in mice. *Homo sapiens* already lives much longer than their closely related species and whether the effects seen in model organisms are reliable predictions for their impact for humans remains an open question. Moreover, the challenge today is not to increase the lifetime of humans, that is already happening. Instead, we should aim to improve healthy years of life by reducing the multimorbidity associated with old age. This challenge has not been adequately addressed, either in model organism research or in clinical studies.

## Thesis overview and objectives

In this chapter, I introduced some of the key concepts of ageing biology, with a focus on the current gap in understanding and the challenging aspects. In the rest of this thesis, I will introduce the computational approaches aiming to address some of these challenges. 

In Section \@ref(introHeterogeneity), I introduced the inter-individual heterogeneity in gene expression as a challenge in ageing research. Although multiple studies have investigated how heterogeneity changes with age, several questions remain unanswered. In Chapter \@ref(HeterogeneityChapter), I will summarise our analyses aiming to understand i) how the inter-individual heterogeneity in gene expression changes with age, at the transcriptome-, pathway-, and gene-level?, ii) how much pre-processing steps and measures of heterogeneity influence the conclusions?, iii) if the change in heterogeneity is linear throughout lifespan or is different between postnatal development (0 to 20 years of age) and ageing (20+ years of age)? 

In Section \@ref(introAgeingDisease), I introduced ageing as a major risk factor for diverse diseases. The exact nature of this relationship, however, is not yet known. In Chapter \@ref(UKBBChapter), I will present an analysis of 116 diseases in the UK Biobank, aiming to characterise the common underlying genetic factor between diseases with similar age profiles concerning their relevance to ageing, functional, and evolutionary characteristics. I will present a list of drugs targeting multiple late-onset diseases. 

In Section \@ref(introInterventions), I summarised the pharmacological interventions that extend lifespan in model organisms. In Chapter \@ref(drugChapter), I will first give an overview of the published computational approaches to find potential lifespan-extending candidates. Then, I will introduce a drug repurposing approach to find drugs that target the characteristic age-related gene expression changes in the human brain. Lastly, I will present a comparison of the results of all published studies, including our approach. 

In Chapter \@ref(concludingRemarks), I will summarise our contributions and future directions of research. 

